config/routes.rb
Rails.application.routes.draw do
  unauthenticated do
    root 'static_pages#about'
  end
  authenticated :user do
    root 'contacts#index'
  end

  devise_for :users,
    controllers: { registrations: 'users/registrations' },
    path: '',
    path_names: {
      sign_in: 'signin',
      sign_out: 'signout',
      registration: 'register',
      sign_up: 'signup'
    }
  as :user do
    get '/signup', to: 'users/registrations#new', as: :user_signup
  end

  get '/about', to: 'static_pages#about'

  resources :contacts
end

app/models/contact.rb
# Contacts: Represents a specific person the user wishes to keep track of
# communications (i.e. Connections) with and various commitments (i.e. Promises)
# made to
class Contact < ApplicationRecord
  default_scope -> { order('created_at ASC') }

  belongs_to :user
  has_many :addresses, as: :addressable
  accepts_nested_attributes_for :addresses, allow_destroy: true

  validates :name,
    presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :create_user_contact, only: [:create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = current_user.contacts.new
    1.times do
      @contact.addresses.build
    end
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    respond_to do |format|
      if @contact.save(contact_params)
        format.html { redirect_to @contact, notice: success_notice }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_contact
    @contact = current_user.contacts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to contacts_path, alert: 'Contact not found in your collection'
  end

  def create_user_contact
    @contact = current_user.contacts.new(contact_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact)
          .permit(:name, :email, :notes,
            addresses_attributes: [:id, :address_type, :primary, :_destroy,
                                   :street1, :city, :state, :zip,
                                   body: [:street1, :city, :state, :zip]])
  end

  def success_notice
    "Successfully added #{@contact.name} to your contacts."
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with model: contact, local: true,
  id: 'contact_form',
  data: {
    contact: contact.to_json,
    addresses_attributes: contact.addresses.to_json(except: [:contact_id, :created_at, :updated_at])
  } do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <fieldset class="form-group">
    <legend>Addresses</legend>

    <section class="form-group"
      v-bind:id="'contact_addresses_attributes_' + index"
      v-for="(address, index) in contact.addresses_attributes">
      <%= render 'addresses/form' %>
    </section>

    <div class="form-group actions">
      <a class="btn btn-secondary form-control" href="#" role="button" v-on:click="addAddress">Add Address</a>
    </div>

  </fieldset>

  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: 'form-control' %>
  </div>

  <div class="form-group actions">
    <%= f.submit 'Submit',
      class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%= render 'application/errors', resource: @contact %>

<div class="card bg-light">
  <h1 class="card-header h4">Editing Contact</h1>
  <div class="card-body">
    <%= render 'form', contact: @contact %>
  </div>
  <div class="card-footer card-footer-actions">
    <div class="btn-group btn-group-sm pull-right" role="group">
      <%= link_to 'Show', @contact, class: 'btn btn-info' %>
      <%= link_to 'Back', contacts_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<% if @contacts.empty? %>
  <div class="jumbotron">
    <h1 class="display-4">
      Welcome to Connectly
    </h1>
    <p class="lead">
      You don't have any contacts yet!
    </p>
    <%= link_to 'Add your first contact', new_contact_path,
      class: 'btn btn-primary btn-lg' %>
  </div>

<% else %>

  <h1>
    <span>Contacts</span>
    <%= link_to '+', new_contact_path,
      class: 'small', title: 'Create a new contact' %>
  </h1>
  <section class="card-columns">
    <% @contacts.each do |contact| %>
      <article class="card">
        <h2 class="card-header card-header-link h4">
          <%= link_to '', contact %>
          <%= contact.name %>
        </h2>
        <div class="card-body">
          <%= contact.email %>
          <%= contact.notes %>
        </div>
        <div class="card-footer card-footer-actions">
          <div class="btn-group btn-group-sm pull-right" role="group">
            <%= link_to 'Edit', edit_contact_path(contact),
              class: 'btn btn-secondary' %>
            <%= link_to 'Delete', contact, method: :delete,
              class: 'btn btn-danger',
              data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </article>
    <% end %>
  </section>

<% end %>

app/views/contacts/new.html.erb
<%= render 'application/errors', resource: @contact %>

<div class="card bg-light">
  <h1 class="card-header h4">New Contact</h1>
  <div class="card-body">
    <%= render 'form', contact: @contact %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', contacts_path %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="row">
  <div class="col-md-7">
    <div class="card d-50">
      <h1 class="h4 card-header">
        <%= @contact.name %>
      </h1>

      <div class="card-body">
        <p><%= @contact.email %></p>
        <p><%= @contact.notes %></p>
      </div>
      <div class="card-body">
        <% @contact.addresses.each do |address| %>
          <p>
            <%= address.body['street1'] %><br />
            <% if address.body['street2'] %>
              <%= address.body['street2'] %><br />
            <% end %>
            <%= address.body['city'] %>, <%= address.body['state'] %> <%= address.body['zip'] %><br />
          </p>
        <% end %>
      </div>

      <div class="card-footer card-footer-actions">
        <div class="btn-group btn-group-sm pull-right" role="group">
          <%= link_to 'Edit', edit_contact_path(@contact),
            class: 'btn btn-secondary' %>
          <%= link_to 'Back', contacts_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>