config/routes.rb
Rails.application.routes.draw do
  unauthenticated do
    root 'static_pages#about'
  end
  authenticated :user do
    root 'contacts#index'
  end

  devise_for :users,
    controllers: { registrations: 'users/registrations' },
    path: '',
    path_names: {
      sign_in: 'signin',
      sign_out: 'signout',
      registration: 'register',
      sign_up: 'signup'
    }
  as :user do
    get '/signup', to: 'users/registrations#new', as: :user_signup
  end

  get '/about', to: 'static_pages#about'

  resources :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up,
      keys: [:username, profile_attributes: [:description]]
    devise_parameter_sanitizer.permit :account_update,
      keys: [:username, profile_attributes: [:description]]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def vue_hidden_tag(attribute, nested_object_name, parent_object_name)
    nested_attributes = "#{nested_object_name.pluralize}_attributes"
    content_tag(:input, nil,
      type: 'hidden',
      'v-model' => "#{nested_object_name}.#{attribute}",
      'v-bind:name' => "'#{parent_object_name}[#{nested_attributes}][' + index + '][#{attribute}]'",
      'v-bind:id' => "'#{parent_object_name}_#{nested_attributes}_' + index + '_#{attribute}'")
  end

  def vue_label(attribute, nested_object_name, parent_object_name)
    nested_attributes = "#{nested_object_name.pluralize}_attributes"
    content_tag(:label,
      class: 'sr-only',
      'v-bind:for' => "'#{parent_object_name}_#{nested_attributes}_' + index + '_#{attribute}'") do
        if block_given?
          yield
        else
          attribute.to_s.humanize.titlecase
        end
      end
  end

  def vue_text_field(attribute, nested_object_name, parent_object_name, placeholder: nil, class: nil)
    nested_attributes = "#{nested_object_name.pluralize}_attributes"
    attribute_name = "#{attribute.to_s.split('_').join('][')}"
    attribute_js_path = attribute.to_s.split('_').join('.')
    content_tag(:input, nil,
      type: 'text', class: 'form-control', placeholder: placeholder,
      'v-model' => "#{nested_object_name}.#{attribute_js_path}",
      'v-bind:name' => "'#{parent_object_name}[#{nested_attributes}][' + index + '][#{attribute_name}]'",
      'v-bind:id' => "'#{parent_object_name}_#{nested_attributes}_' + index + '_#{attribute}'")
  end

end

app/views/application/navbar/_guest_menu.html.erb
<li class="nav-item">
  <%= link_to 'Sign in', new_user_session_path,
    class: 'btn btn-outline-light mr-lg-2 my-2 my-lg-0' %>
</li>
<li class="nav-item">
  <%= link_to 'Sign up', user_signup_path,
    class: 'btn btn-primary ml-lg-2 my-2 my-lg-0' %>
</li>

app/views/application/navbar/_user_menu.html.erb
<li class="nav-item dropdown">
  <% navbar_avatar_toggle_class =
       "navbar-avatar-toggle-#{current_user.avatar? ? 'hide' : 'show'}" %>
  <a id="navbarUserMenu" href="#"
     class="nav-link dropdown-toggle <%= navbar_avatar_toggle_class -%>"
     data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <% if current_user.profile.avatar.attached? %>
      <%= image_tag current_user.profile.avatar.variant(resize: '80x80'),
        class: 'navbar-avatar' %>
    <% end %>
    <span class="navbar-avatar-toggle-text">
      <%= current_user.username %>
    </span>
  </a>

  <div class="dropdown-menu dropdown-menu-right"
       aria-labelledby="navbarUserMenu">
    <%= link_to 'Edit Account', edit_user_registration_path,
      class: 'dropdown-item' %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete,
      class: 'dropdown-item' %>
  </div>
</li>